version: '3.8'

services:

 redis:
    image: redis:7.0.11-alpine

 django:
    container_name: django
    build:
      context: ./_celery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./_celery:/Users/Mahammad/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

 celery:
    container_name: celery
    build:
      context: ./_celery
    command: celery --app=_celery worker -l INFO -Q celery,celery:1,celery:2,celery:3
    volumes:
      - ./_celery:/Users/Mahammad/app
  
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django
  
#  celerynew:
#     container_name: celerynew
#     build:
#       context: ./celeryworker
#     command: celery -A celerytask worker --l INFO
#     volumes:
#       - ./celeryworker:/Users/Mahammad/app
  
#     depends_on:
#       - redis
#       - django

